apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-build-pipeline
spec:
  finally:
  - name: show-sbom
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    taskRef:
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-show-sbom:0.1@sha256:48e7a4915f07ab0b55cc76a906c1e350c86053aa659e2d1d4aecf7e3cab06bad
      - name: kind
        value: task
      resolver: bundles
  - name: show-summary
    params:
    - name: pipelinerun-name
      value: $(context.pipelineRun.name)
    - name: git-url
      value: $(tasks.clone-repository-amd64.results.url)?rev=$(tasks.clone-repository-amd64.results.commit)
    - name: image-url
      value: $(params.output-image)
    - name: build-task-status
      value: $(tasks.build-container-amd64.status)
    taskRef:
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-summary:0.2@sha256:c2f3d37763fb6fe46af4b0a861eb350d2ae5cc7677046e7d96a42f6db3d2f732
      - name: kind
        value: task
      resolver: bundles
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  params:
  - description: Source Repository URL
    name: git-url
    type: string
  - default: ""
    description: Revision of the Source Repository
    name: revision
    type: string
  - description: Fully Qualified Output Image
    name: output-image
    type: string
  - default: .
    description: Path to the source code of an application's component from where
      to build image.
    name: path-context
    type: string
  - default: Dockerfile
    description: Path to the Dockerfile inside the context specified by parameter
      path-context
    name: dockerfile
    type: string
  - default: "false"
    description: Force rebuild image
    name: rebuild
    type: string
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ""
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: "false"
    description: Java build
    name: java
    type: string
  - default: ""
    description: Image tag expiration time, time values could be something like
      1h, 2d, 3w for hours, days, and weeks, respectively.
    name: image-expires-after
  - default: "false"
    description: Build a source image.
    name: build-source-image
    type: string
  - default: ""
    description: Path to a file with build arguments which will be passed to podman
      during build
    name: build-args-file
    type: string

  results:
  - description: ""
    name: IMAGE_URL
    value: $(tasks.build-container.results.IMAGE_URL)
  - description: ""
    name: IMAGE_DIGEST
    value: $(tasks.build-container.results.IMAGE_DIGEST)
  - description: ""
    name: CHAINS-GIT_URL
    value: $(tasks.clone-repository-amd64.results.url)
  - description: ""
    name: CHAINS-GIT_COMMIT
    value: $(tasks.clone-repository-amd64.results.commit)
  - description: ""
    name: JAVA_COMMUNITY_DEPENDENCIES
    value: $(tasks.build-container-amd64.results.JAVA_COMMUNITY_DEPENDENCIES)

  tasks:
  - name: init
    params:
    - name: image-url
      value: $(params.output-image)
    - name: rebuild
      value: $(params.rebuild)
    - name: skip-checks
      value: $(params.skip-checks)
    taskRef:
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.4@sha256:d308236254add26d2c71fbf0d5d0736b598f098c48711851aacad2baebabfb55
      - name: kind
        value: task
      resolver: bundles

  # amd64

  - name: clone-repository-amd64
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    runAfter:
    - init
    taskRef:
      params:
      - name: name
        value: git-clone
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone:0.1@sha256:2175fdd1ab932727d7a539ef260f32a127a004c61257f974ffaf23863763de9b
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: output
      workspace: workspace-amd64
    - name: basic-auth
      workspace: git-auth

  - name: prefetch-dependencies-amd64
    params:
    - name: input
      value: $(params.prefetch-input)
    - name: dev-package-managers
      value: 'true'
    runAfter:
    - clone-repository-amd64
    taskRef:
      params:
      - name: name
        value: prefetch-dependencies
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-prefetch-dependencies:0.3@sha256:d9ee459a5d22f6690aab9ef128dd7e18e829d5c5afa093672fe37e53bb68e66c
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.prefetch-input)
      operator: notin
      values:
      - ""
    workspaces:
    - name: source
      workspace: workspace-amd64
    - name: git-basic-auth
      workspace: git-auth

  - name: build-container-amd64
    params:
    - name: IMAGE
      value: $(params.output-image)-amd64
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository-amd64.results.commit)
    - name: BUILD_ARGS_FILE
      value: $(params.build-args-file)
    - name: PLATFORM
      value: linux/amd64
    runAfter:
    - prefetch-dependencies-amd64
    taskRef:
      params:
      - name: name
        value: buildah-remote
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-buildah-remote:0.9@sha256:a03e4c5f99e4b37070b5c101a13917d1942878475a2ecc6b87dc54741188c0e3
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace-amd64

  # arm64

  - name: clone-repository-arm64
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    runAfter:
    - init
    taskRef:
      params:
      - name: name
        value: git-clone
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone:0.1@sha256:2175fdd1ab932727d7a539ef260f32a127a004c61257f974ffaf23863763de9b
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: output
      workspace: workspace-arm64
    - name: basic-auth
      workspace: git-auth

  - name: prefetch-dependencies-arm64
    params:
    - name: input
      value: $(params.prefetch-input)
    - name: dev-package-managers
      value: 'true'
    runAfter:
    - clone-repository-arm64
    taskRef:
      params:
      - name: name
        value: prefetch-dependencies
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-prefetch-dependencies:0.3@sha256:d9ee459a5d22f6690aab9ef128dd7e18e829d5c5afa093672fe37e53bb68e66c
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.prefetch-input)
      operator: notin
      values:
      - ""
    workspaces:
    - name: source
      workspace: workspace-arm64
    - name: git-basic-auth
      workspace: git-auth

  - name: build-container-arm64
    params:
    - name: IMAGE
      value: $(params.output-image)-arm64
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository-arm64.results.commit)
    - name: BUILD_ARGS_FILE
      value: $(params.build-args-file)
    - name: PLATFORM
      value: linux/arm64
    runAfter:
    - prefetch-dependencies-arm64
    taskRef:
      params:
      - name: name
        value: buildah-remote
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-buildah-remote:0.9@sha256:a03e4c5f99e4b37070b5c101a13917d1942878475a2ecc6b87dc54741188c0e3
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace-arm64

  - name: build-container
    params:
    - name: IMAGE
      value: $(params.output-image)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository-amd64.results.commit)
    - name: IMAGES
      value:
        - $(tasks.build-container-amd64.results.IMAGE_URL)@$(tasks.build-container-amd64.results.IMAGE_DIGEST)
        - $(tasks.build-container-arm64.results.IMAGE_URL)@$(tasks.build-container-arm64.results.IMAGE_DIGEST)
    runAfter:
    - build-container-amd64
    - build-container-arm64
    taskRef:
      params:
      - name: name
        value: build-image-manifest
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-build-image-manifest:0.1@sha256:3cdad855f144697e71197f4ca3266f4d9b4c730af50a31c18e4c2a98dd0917a9
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"

  - name: build-source-image
    params:
    - name: BINARY_IMAGE
      value: $(params.output-image)
    - name: BASE_IMAGES
      # NOTICE:
      value: $(tasks.build-container-amd64.results.BASE_IMAGES_DIGESTS)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: source-build
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-source-build:0.3@sha256:4995ea88b09b16620a1e313c968b894ace6b82c310239c566d9824a83d233d41
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    - input: $(params.build-source-image)
      operator: in
      values:
      - "true"
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  - name: deprecated-base-image-check
    params:
    - name: BASE_IMAGES_DIGESTS
      value: $(tasks.build-container-amd64.results.BASE_IMAGES_DIGESTS)
    - name: IMAGE_URL
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-deprecated-image-check:0.5@sha256:4d452338516ee1fe0f3243a38310aa8cba41c89c0fa4813dd8a3b5ad587542c6
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"

  - name: clair-scan
    params:
    - name: image-digest
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: clair-scan
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-clair-scan:0.3@sha256:d146c60b93f8f06262dbb74f248a72657b42f951e3943840b303e9abdb3f6140
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"

  - name: ecosystem-cert-preflight-checks
    params:
    - name: image-url
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: ecosystem-cert-preflight-checks
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:66cb948dda9bab8b35a4145dd6eb7d83e9773b81e51b0e27dd3d7c9d64bba165
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"

  - name: sast-snyk-check
    runAfter:
    - clone-repository-amd64
    taskRef:
      params:
      - name: name
        value: sast-snyk-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-sast-snyk-check:0.4@sha256:053dd7eb45fe2b975644a57428b200e4be0f19c2240fed6ea6843bd7126823ff
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  - name: clamav-scan
    params:
    - name: image-digest
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: clamav-scan
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-clamav-scan:0.3@sha256:f9f87f325b558dcef52460a5aa7173034aca2b762a2a2785eac4caddd509e1eb
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sbom-json-check
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: sbom-json-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-sbom-json-check:0.2@sha256:f002bf24b093cbd8debf34dc0d550ff3cd37a84515b04d60cb08e126c660de48
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: apply-tags
    params:
    - name: IMAGE
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: ADDITIONAL_TAGS
      value:
      - devel
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: apply-tags
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-apply-tags:0.3@sha256:73b5a2cd3ebf8791c66e749c7c2e9c34eb7903929ec8f483c687be72bbeab39d
      - name: kind
        value: task
      resolver: bundles

  - name: push-build-file
    runAfter:
    - build-container
    taskRef:
      resolver: bundles
      params:
      - name: kind
        value: task
      - name: name
        value: push-build-file
      - name: bundle
        value: quay.io/konflux-ci/pull-request-builds:push-build-file-0.1@sha256:08e7852647a2cdd7d377994106495a08bc7e1b437b5ef57afb6dc89b54f81374
    params:
    - name: IMAGE
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: BUILD_FILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  workspaces:
  - name: workspace-amd64
  - name: workspace-arm64
  - name: git-auth
    optional: true
