apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-build-pipeline
spec:
  finally:
  - name: show-sbom
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    taskRef:
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:04994df487ee886adbe60a8a5866647fbdfd53cc26f7b2554272ba51bf7af29e
      - name: kind
        value: task
      resolver: bundles
  - name: show-summary
    params:
    - name: pipelinerun-name
      value: $(context.pipelineRun.name)
    - name: git-url
      value: $(tasks.clone-repository-amd64.results.url)?rev=$(tasks.clone-repository-amd64.results.commit)
    - name: image-url
      value: $(params.output-image)
    - name: build-task-status
      value: $(tasks.build-container-amd64.status)
    taskRef:
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:526555c9d77ca9e97c52ee6bfcd097fbedc1f3442084367c936af4faa69951e8
      - name: kind
        value: task
      resolver: bundles
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  params:
  - description: Source Repository URL
    name: git-url
    type: string
  - default: ""
    description: Revision of the Source Repository
    name: revision
    type: string
  - description: Fully Qualified Output Image
    name: output-image
    type: string
  - default: .
    description: Path to the source code of an application's component from where
      to build image.
    name: path-context
    type: string
  - default: Dockerfile
    description: Path to the Dockerfile inside the context specified by parameter
      path-context
    name: dockerfile
    type: string
  - default: "false"
    description: Force rebuild image
    name: rebuild
    type: string
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ""
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: "false"
    description: Java build
    name: java
    type: string
  - default: ""
    description: Image tag expiration time, time values could be something like
      1h, 2d, 3w for hours, days, and weeks, respectively.
    name: image-expires-after
  - default: "false"
    description: Build a source image.
    name: build-source-image
    type: string
  - default: ""
    description: Path to a file with build arguments which will be passed to podman
      during build
    name: build-args-file
    type: string

  results:
  - description: ""
    name: IMAGE_URL
    value: $(tasks.build-container.results.IMAGE_URL)
  - description: ""
    name: IMAGE_DIGEST
    value: $(tasks.build-container.results.IMAGE_DIGEST)
  - description: ""
    name: CHAINS-GIT_URL
    value: $(tasks.clone-repository-amd64.results.url)
  - description: ""
    name: CHAINS-GIT_COMMIT
    value: $(tasks.clone-repository-amd64.results.commit)
  - description: ""
    name: JAVA_COMMUNITY_DEPENDENCIES
    value: $(tasks.build-container-amd64.results.JAVA_COMMUNITY_DEPENDENCIES)

  tasks:
  - name: init
    params:
    - name: image-url
      value: $(params.output-image)
    - name: rebuild
      value: $(params.rebuild)
    - name: skip-checks
      value: $(params.skip-checks)
    taskRef:
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:a482890d072df3aff9cf5db0ff2b9ec04fa6bb006cfd9da9817805fdd11a73f5
      - name: kind
        value: task
      resolver: bundles

  # amd64

  - name: clone-repository-amd64
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    runAfter:
    - init
    taskRef:
      params:
      - name: name
        value: git-clone
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:7db7ad9653dccc771407cb0294487cf4be9064fa782ffad7e983db1a8ba57e21
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: output
      workspace: workspace-amd64
    - name: basic-auth
      workspace: git-auth

  - name: prefetch-dependencies-amd64
    params:
    - name: input
      value: $(params.prefetch-input)
    - name: dev-package-managers
      value: 'true'
    runAfter:
    - clone-repository-amd64
    taskRef:
      params:
      - name: name
        value: prefetch-dependencies
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies:0.1@sha256:b0f19fe021457caeda126e861d08ad59007f64f954119e2531f7786bd76f98c7
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.prefetch-input)
      operator: notin
      values:
      - ""
    workspaces:
    - name: source
      workspace: workspace-amd64
    - name: git-basic-auth
      workspace: git-auth

  - name: build-container-amd64
    params:
    - name: IMAGE
      value: $(params.output-image)-amd64
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository-amd64.results.commit)
    - name: BUILD_ARGS_FILE
      value: $(params.build-args-file)
    - name: PLATFORM
      value: linux/amd64
    runAfter:
    - prefetch-dependencies-amd64
    taskRef:
      params:
      - name: name
        value: buildah-remote
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote:0.1@sha256:6721ce51ab452ea5841742f3d0c5bc1402ab107f4e8bf42fcee679b4da2f25db
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace-amd64

  # arm64

  - name: clone-repository-arm64
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    runAfter:
    - init
    taskRef:
      params:
      - name: name
        value: git-clone
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:7db7ad9653dccc771407cb0294487cf4be9064fa782ffad7e983db1a8ba57e21
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: output
      workspace: workspace-arm64
    - name: basic-auth
      workspace: git-auth

  - name: prefetch-dependencies-arm64
    params:
    - name: input
      value: $(params.prefetch-input)
    - name: dev-package-managers
      value: 'true'
    runAfter:
    - clone-repository-arm64
    taskRef:
      params:
      - name: name
        value: prefetch-dependencies
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies:0.1@sha256:b0f19fe021457caeda126e861d08ad59007f64f954119e2531f7786bd76f98c7
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.prefetch-input)
      operator: notin
      values:
      - ""
    workspaces:
    - name: source
      workspace: workspace-arm64
    - name: git-basic-auth
      workspace: git-auth

  - name: build-container-arm64
    params:
    - name: IMAGE
      value: $(params.output-image)-arm64
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository-arm64.results.commit)
    - name: BUILD_ARGS_FILE
      value: $(params.build-args-file)
    - name: PLATFORM
      value: linux/arm64
    runAfter:
    - prefetch-dependencies-arm64
    taskRef:
      params:
      - name: name
        value: buildah-remote
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote:0.1@sha256:6721ce51ab452ea5841742f3d0c5bc1402ab107f4e8bf42fcee679b4da2f25db
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace-arm64

  - name: build-container
    params:
    - name: IMAGE
      value: $(params.output-image)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository-amd64.results.commit)
    - name: IMAGES
      value:
        - $(tasks.build-container-amd64.results.IMAGE_URL)@$(tasks.build-container-amd64.results.IMAGE_DIGEST)
        - $(tasks.build-container-arm64.results.IMAGE_URL)@$(tasks.build-container-arm64.results.IMAGE_DIGEST)
    runAfter:
    - build-container-amd64
    - build-container-arm64
    taskRef:
      params:
      - name: name
        value: build-image-manifest
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-build-image-manifest:0.1@sha256:a02a561e2cdc4b7a90302f4ebe67fa8fd48eb14b5390370c9ebf43454cef2a88
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"

  - name: build-source-image
    params:
    - name: BINARY_IMAGE
      value: $(params.output-image)
    - name: BASE_IMAGES
      # NOTICE:
      value: $(tasks.build-container-amd64.results.BASE_IMAGES_DIGESTS)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: source-build
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-source-build:0.1@sha256:577eab2b57c604a4efc4fd4424eb416f6fbe730226787fd81174137145150730
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    - input: $(params.build-source-image)
      operator: in
      values:
      - "true"
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  - name: deprecated-base-image-check
    params:
    - name: BASE_IMAGES_DIGESTS
      value: $(tasks.build-container-amd64.results.BASE_IMAGES_DIGESTS)
    - name: IMAGE_URL
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.4@sha256:febec4cf37d92c1623cdd61c2e4b1647dc13d1ff75f44b8cb24569eb215b583d
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"

  - name: clair-scan
    params:
    - name: image-digest
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: clair-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.1@sha256:bd5ec7081ead5bc28dce14defa6821fc61a8d52700c512dc6b0d071fa98d929b
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"

  - name: ecosystem-cert-preflight-checks
    params:
    - name: image-url
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: ecosystem-cert-preflight-checks
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.1@sha256:fd146c14794b6bc15384359d0dc8afc8a4a5f2b167503c6288ec2d86c8cbc9c0
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"

  - name: sast-snyk-check
    runAfter:
    - clone-repository-amd64
    taskRef:
      params:
      - name: name
        value: sast-snyk-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check:0.1@sha256:0dd81b8523426b6a2dc8718917cd6538ed3a7eaed8840f60bb0bff2719771d9f
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  - name: clamav-scan
    params:
    - name: image-digest
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: clamav-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.1@sha256:a01f94db2bdf6f9a86e1e9cc256e1b7c26cb4d0253e67579196bd8ffbc33a7ca
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sbom-json-check
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    runAfter:
    - build-container-amd64
    taskRef:
      params:
      - name: name
        value: sbom-json-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sbom-json-check:0.1@sha256:9c475babf202e0b04f587f301f020970829ecbe766fe20bbfd0b6ece7628ad7f
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: apply-tags
    params:
    - name: IMAGE
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: ADDITIONAL_TAGS
      value:
      - devel
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: apply-tags
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:c5ed9ff3865b8805e6e17c0fd4fb601f92cafa2c6c11ee87e72884ee58088ac9
      - name: kind
        value: task
      resolver: bundles

  - name: push-build-file
    runAfter:
    - build-container
    taskRef:
      resolver: bundles
      params:
      - name: kind
        value: task
      - name: name
        value: push-build-file
      - name: bundle
        value: quay.io/konflux-ci/pull-request-builds:push-build-file-0.1@sha256:08e7852647a2cdd7d377994106495a08bc7e1b437b5ef57afb6dc89b54f81374
    params:
    - name: IMAGE
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: BUILD_FILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    workspaces:
    - name: workspace
      workspace: workspace-amd64

  workspaces:
  - name: workspace-amd64
  - name: workspace-arm64
  - name: git-auth
    optional: true
