---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: multi-arch-builds
  namespace: cqi-tenant
spec:
  displayName: multi-arch-builds
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: bing-wallpaper
  namespace: cqi-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
spec:
  application: multi-arch-builds
  componentName: bing-wallpaper
  source:
    git:
      revision: main
      url: https://github.com/my-konflux-stuff/multi-arch-builds
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  name: imagerepository-for-bing-wallpaper
  namespace: cqi-tenant
  labels:
    appstudio.redhat.com/application: multi-arch-builds
    appstudio.redhat.com/component: bing-wallpaper
spec:
  image:
    name: cqi-tenant/bing-wallpaper
    visibility: public
  notifications:
  - config:
      url: https://bombino.api.redhat.com/v1/sbom/quay/push
    event: repo_push
    method: webhook
    title: SBOM-event-to-Bombino
